<a href="https://colab.research.google.com/github/tisake/DERT/blob/master/lab_190227.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# String และ List 
1. เขียนสคริปท์ให้ผู้ใช้ป้อนตัวเลขมาสองตัว แล้วพิมพ์ผลบวก

1. ใช้ list comprehension สร้างลิสท์ต่อไปนี้
[3, 4, 5]
[5, 4, 3, 2, 1] 
[2, 4, 8, 16, 32]

1. รับอินพุทเป็นหมายเลขโทรศัพท์เช่น 08-1234-5555 แล้วนำเลขทั้งสามชุดมาบวกกัน
1. **extra point** เก็บโค้ดใน github


In [0]:
a = int(input())
b = int(input())
print('result is %d' %(a + b))

2
3
result is 5


In [17]:
a = [i+3 for i in range(3)]
print(a)
a = [5-i for i in range(5)]
print(a)
a = [2**(i+1) for i in range(5)]
print(a)

[3, 4, 5]
[5, 4, 3, 2, 1]
[2, 4, 8, 16, 32]


In [18]:
s = input()
a = s.___
print(___(a))

AttributeError: ignored

# ฟังก์ชัน 
- เขียนฟังก์ชันหาค่าเฉลี่ยของลิสท์ ทดสอบโดยส่งลิสท์ [1, 2, 3, 4, 5]
- หาค่ามากที่สุดในลิสท์ [42, 911, 17, 286]
- หาเลขที่หลักหน่วยที่มากที่สุดในลิสท์ [42, 911, 17, 286]
- **extra point** หา index ที่เก็บค่าที่น้อยที่สุดในลิสท์


In [26]:
a = [1, 2, 3, 4, 5]
def avg(a):
  return sum(a)/len(a)

avg([1, 2, 3, 4, 5])

3.0

In [24]:
a = [42, 911, 17, 286]
max(a,key=lambda x: x%10)

17

In [27]:
max(a, key=lambda x: x%10)

5

In [0]:
min(range(len(a)), key=___)

# numpy
- สร้างอาร์เรย์ขนาด 100 ที่มีค่า 9 ทั้งหมด
- สร้างอาร์เรย์ขนาด 2x2 
- สร้างอาร์เรย์ขนาด 2x3x3 
- สร้างอาร์เรย์ขนาด 100 โดยใส่เลขสุ่ม กรองเลขที่น้อยกว่า 0.8 ผลการกรองมีขนาดเท่าใด
- **extra point** สร้างอาร์เรย์ขนาด 2x2 ที่มีแถวแรกมีค่า 0 และแถวที่สองมีค่า 1

In [53]:
import numpy as np
a = np.full(100, 9)
np.all(a == 9) and a.shape[0] == 100


a = a.reshape(2,-1)

b = np.random.rand(100)
c = b(b<0.8)
b

TypeError: ignored

# MLP

## Prepare Data

In [0]:
from google.colab import files
uploaded = files.upload()

Saving wine.csv to wine.csv


In [0]:
import pandas as pd

df = pd.read_csv('wine.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  rw  
0      9.4        5   0  
1      9.8        5   0  
2      9.8        5   0  
3      9.8        6   0  
4      9.4        5   0

In [0]:
X = df[df.columns[:-1]].values
Y = df[df.columns[-1]].values

array([0, 0, 0, ..., 1, 1, 1])

In [0]:
f = np.random.rand(X.shape[0]) < 0.8
Xtrain = X[f]
Xtest  = X[~f]
Ytrain = Y[f]
Ytest  = Y[~f]

## Create a Model

## Test the Model

In [0]:
test_loss, test_acc = model.evaluate(Xtest, Ytest)  

print('Test accuracy:', test_acc)

1350/1350 [==============================] - 0s 55us/step
Test accuracy: 0.9881481481481481


In [48]:
import numpy as np
a = np.array([3,2,4,6,2,1])
a = a.reshape(2,3)

z = np.zeros(10)
o = np.ones(10).reshape(2,-1)

b = np.arange(5)


b = np.random.rand(5)
b = np.fromfunction(lambda i : -i, (5,))
b

array([-0., -1., -2., -3., -4.])

In [72]:
import numpy as np
a1 = np.zeros(100)+9
a = np.full(100, 9)

b1 = np.zeros((2,2))
b = np.zeros(4).reshape(2,2)

c1 = np.zeros((2,2,3))
c = np.zeros(18).reshape(2,3,3)

d = np.random.rand(100)
e = d[d<0.8]
e.shape

f  = np.array([[0,0],[1,1]])
f

array([[0, 0],
       [1, 1]])